### PR TITLE
Classes

### PR DESCRIPTION
**Pull request by XigaChad**
Can you implement classes for this lang? I would like to see if it is possible.

### CODE REVIEW

**Comment by Griiimon** [comment]
There is a pull request including code for this feature in the original project 

https://github.com/davidcallanan/py-myopl-code/pull/19

**Comment by angelcaru** [comment]
It's been a few years but... sure! Shouldn't be too hard to port [Pixelthegreat](https://github.com/Pixelthegreat)'s code to my project.

**Comment by angelcaru** [comment]
> Shouldn't be too hard to port [Pixelthegreat](https://github.com/Pixelthegreat)'s code to my project.

It was.

**Comment by angelcaru** [comment]
I made a branch (https://github.com/angelcaru/myopl-plus-plus/tree/classes) for the migration of the class code. Just in case anyone can figure out what the fuck is going on.

**Comment by angelcaru** [comment]
[It's not classes, but it's honest work](https://github.com/angelcaru/myopl-plus-plus/commit/d04b7f235627d0d3d8380f9620482f2f90511b2a?diff=unified&w=0)

**Pull request closed without merging**
